--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/UltimateCasino
build-by-default: true
branches:
  - master
projects:
  UltimateCasino:
    libs:
      - src: PJZ9n/PluginUtils2/PluginUtils2
        version: 1.1.2
...
